/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 m16_a2_rifle.glb 
Author: Luchador (https://sketchfab.com/Luchador90)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m16-a2-rifle-20c4bb925ca349c6b33aca176b8affba
Title: M16 A2 Rifle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function M16Model(props) {
  const { nodes, materials } = useGLTF('/m16_a2_rifle.glb')
  return (
    <group position={[1,0,1]} {...props} dispose={null}>
      <group position={[-7.479, -2.902, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.24}>
        <mesh geometry={nodes.magazine_m16a2_0.geometry} material={materials.m16a2} position={[31.245, -11, 12.543]} />
      </group>
      <group position={[-9.161, 6.336, 1.741]} rotation={[-Math.PI / 2, 0, 0]} scale={0.24}>
        <mesh geometry={nodes.ejection_port_cover_m16a2_0.geometry} material={materials.m16a2} position={[38.150, 7.250, -26.400]} />
      </group>
      <mesh geometry={nodes.m16a2_m16a2_0.geometry} material={materials.m16a2} rotation={[-Math.PI / 2, 0, 0]} scale={0.24} />
    </group>
  )
}

useGLTF.preload('/m16_a2_rifle.glb')
