/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 1860_spencer_carbine_with_engravings.glb 
Author: EvolvedDitmur (https://sketchfab.com/EvolvedDitmur)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1860-spencer-carbine-with-engravings-94a99d051c6b42deb67e2607a83d2f11
Title: 1860 Spencer Carbine with engravings
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Spencer1860Model(props) {
  const { nodes, materials } = useGLTF('/1860_spencer_carbine_with_engravings.glb')
  return (
    <group position={[-1,-2,0]} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Handguard_brace19_Cloth_0.geometry} material={materials.Cloth} />
        <mesh geometry={nodes.Handguard_brace18_Metal_brace_0.geometry} material={materials.Metal_brace} />
        <mesh geometry={nodes.pCylinder48_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Handguard1_Gun_Wood_0.geometry} material={materials.Gun_Wood} />
        <mesh geometry={nodes.Front_iron_sight_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Hammer_Moving_parts_0.geometry} material={materials.Moving_parts} />
        <mesh geometry={nodes.Sling_bar_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Receiver1_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Trigger_base_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Ejector_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Handguard_brace2_Metal_brace_0.geometry} material={materials.Metal_brace} />
        <mesh geometry={nodes.Stock1_Gun_Wood_0.geometry} material={materials.Gun_Wood} />
        <mesh geometry={nodes.Stock_brace_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Trigger1_Moving_parts_0.geometry} material={materials.Moving_parts} />
        <mesh geometry={nodes.Hammer_Brace_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Lever1_Moving_parts_0.geometry} material={materials.Moving_parts} />
        <mesh geometry={nodes.pasted__pasted__Magazine_Shutter1_Moving_parts_0.geometry} material={materials.Moving_parts} />
        <mesh geometry={nodes.pCube69_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.pCube65_Moving_parts_0.geometry} material={materials.Moving_parts} />
        <mesh geometry={nodes.pCube62_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.Handguard_brace33_Cloth_0.geometry} material={materials.Cloth} />
        <mesh geometry={nodes.Handguard_brace34_Cloth_0.geometry} material={materials.Cloth} />
        <mesh geometry={nodes.Handguard_brace37_Metal_brace_0.geometry} material={materials.Metal_brace} position={[20.846, 0, 0]} />
        <mesh geometry={nodes.Screw_grip_01_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface3_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface4_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface5_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface6_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface7_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface8_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface9_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface10_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface11_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.polySurface13_Gunmetal_0.geometry} material={materials.Gunmetal} />
        <mesh geometry={nodes.pCylinder79_Gunmetal_0.geometry} material={materials.Gunmetal} position={[388.384, 301.242, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.103, 2.149, 0.103]} />
      </group>
    </group>
  )
}

useGLTF.preload('/1860_spencer_carbine_with_engravings.glb')
