/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ots-14_groza.glb 
Author: Artem P (https://sketchfab.com/temp0.crazy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ots-14-groza-402d762908ec4759bf919279d51b0de5
Title: OTs-14 "Groza"
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function OTs14GrozaModel(props) {
  const { nodes, materials } = useGLTF('/ots-14_groza.glb')
  return (
    <group scale={0.013} rotation={[0,-1.4,0]} {...props} dispose={null}>
      <mesh geometry={nodes.BodyDetail1_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cover_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.UpperHandleBoltBack2_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.UpperHandleDetail_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.UpperHandleBoltBack1_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ModeSwitcherDetail_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ModeSwitcher_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.FrontDetail2_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.CartridgeDetail2_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.CartridgeClamping_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.GasTube_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Bolt_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ReceiverClamping2_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ReceiverClamping1_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Body_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.WeaponDetail1_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.WeaponDetail2_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.BodyDetail2_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Barrel_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ButtClamping2_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ButtClamping4_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Shutter_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.CylinderShutter_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Receiver_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ButtClamping3_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ButtClamping1_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.CartridgeDetail1_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.FrontDetail1_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.UpperHandleBolt_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.UpperHandle_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.GasChamber_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.FrontBox_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Trigger_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Handle_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Butt_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cartridge_low000__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/ots-14_groza.glb')
