/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 mauser_k98_sniper_rilfe.glb 
Author: wolfstain12 (https://sketchfab.com/wolfstain12)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mauser-k98-sniper-rilfe-ce1301fd58a44ab5ae2aa7c0bc07f52b
Title: Mauser K98 Sniper rilfe
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function K98Model(props) {
  const { nodes, materials } = useGLTF('/mauser_k98_sniper_rilfe.glb')
  return (
    <group position={[-0.5,-0.2,0]} scale={0.05} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['09___Default']} position={[-103.005, -6.326, 5.351]} />
      </group>
    </group>
  )
}

useGLTF.preload('/mauser_k98_sniper_rilfe.glb')
