/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ak_12.glb 
Author: Revver (https://sketchfab.com/Revver)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ak-12-47b96856872b409d90281ae79b2429f0
Title: Ak 12
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ak12Model(props) {
  const { nodes, materials } = useGLTF('/ak_12.glb')
  return (
    <group position={[0,0.5,0]} scale={2} rotation={[0,-1.5,0]} {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[13.314, 4.523, 15.586]} rotation={[-0.143, 1.568, 1.71]} scale={100}>
          <mesh geometry={nodes.Box003_high_uv_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Slice002_high_uv_0.geometry} material={materials.material} position={[0.086, -1.023, 0.004]} />
        </group>
        <group position={[13.643, -5.021, -103.827]} rotation={[-1.575, 0, 3.139]} scale={100}>
          <mesh geometry={nodes.Cube_high_uv_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Slice_high_uv_0.geometry} material={materials.material} position={[0, -0.945, -0.152]} />
        </group>
        <group position={[12.748, 16.277, 216.329]} rotation={[-0.143, 1.568, 1.71]} scale={100}>
          <mesh geometry={nodes.Box_high_uv_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cutter020_high_uv_0.geometry} material={materials.material} position={[-0.035, -0.003, -0.061]} rotation={[Math.PI, 0, Math.PI / 2]} />
        </group>
        <group position={[13.432, -19.11, -25.658]} rotation={[-1.598, 0, 3.139]} scale={100}>
          <mesh geometry={nodes.Cube003_high_uv_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cutter027_high_uv_0.geometry} material={materials.material} position={[0.049, -0.003, -0.005]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
        </group>
        <group position={[13.195, 18.603, 54.607]} rotation={[-1.575, 0, 3.139]} scale={100}>
          <mesh geometry={nodes.Cube017_high_uv_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cutter072_high_uv_0.geometry} material={materials.material} position={[0.073, -0.015, -0.052]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Slice001_high_uv_0.geometry} material={materials.material} position={[0.059, -0.01, 0.08]} />
          <mesh geometry={nodes.Cutter083_high_uv_0.geometry} material={materials.material} position={[-0.078, -0.007, -0.039]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cutter085_high_uv_0.geometry} material={materials.material} position={[-0.059, -0.01, 0.073]} rotation={[-Math.PI / 2, -Math.PI / 2, 0]} />
        </group>
        <group position={[4.777, 26.073, 59.02]} rotation={[-1.575, 0, 3.139]} scale={100}>
          <mesh geometry={nodes.Cube018_high_uv_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cutter079_high_uv_0.geometry} material={materials.material} position={[0.001, -0.062, -0.023]} rotation={[Math.PI, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cutter081_high_uv_0.geometry} material={materials.material} position={[0.003, 0.02, -0.023]} rotation={[Math.PI, Math.PI / 2, 0]} />
        </group>
        <group position={[13.341, -56.251, 12.468]} rotation={[-0.143, 1.568, 1.714]} scale={100}>
          <mesh geometry={nodes.Box004_high_uv_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cutter095_high_uv_0.geometry} material={materials.material} position={[-0.329, 0.098, 0.065]} rotation={[0, 0.023, -0.22]} scale={[0.617, 0.616, 1]} />
        </group>
        <group position={[13.341, -56.26, 12.477]} rotation={[-0.143, 1.568, 1.714]} scale={[100, 100, 103.249]}>
          <mesh geometry={nodes.Box004_Piece_high_uv_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Cutter093_high_uv_0.geometry} material={materials.material} position={[-0.376, 0.115, -0.004]} rotation={[-Math.PI / 2, -1.38, 1.571]} />
        </group>
        <mesh geometry={nodes.Cylinder_high_uv_0.geometry} material={materials.material} position={[12.997, 3.651, 128.384]} rotation={[3.138, 0.003, 3.141]} scale={100} />
        <mesh geometry={nodes.Cylinder_Piece_high_uv_0.geometry} material={materials.material} position={[12.735, 4.027, 223.022]} rotation={[3.138, 0.003, 3.141]} scale={100} />
        <mesh geometry={nodes.Box005_high_uv_0.geometry} material={materials.material} position={[13.572, -44.232, -72.522]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Box003_Plate_high_uv_0.geometry} material={materials.material} position={[13.283, 25.157, 22.007]} rotation={[-0.143, 1.568, 1.71]} scale={100} />
        <mesh geometry={nodes.Cube001_high_uv_0.geometry} material={materials.material} position={[12.747, -3.431, 219.538]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube004_high_uv_0.geometry} material={materials.material} position={[13.481, -23.281, -42.588]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube005_high_uv_0.geometry} material={materials.material} position={[13.487, -14.27, -46.318]} rotation={[-1.707, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder001_high_uv_0.geometry} material={materials.material} position={[12.991, 16.627, 128.71]} rotation={[3.138, 0.003, 3.141]} scale={100} />
        <mesh geometry={nodes.Cube006_high_uv_0.geometry} material={materials.material} position={[13.197, -7.272, 57.543]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube007_high_uv_0.geometry} material={materials.material} position={[1.431, -4.018, -62.813]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube008_high_uv_0.geometry} material={materials.material} position={[13.537, 28.267, -70.238]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube009_high_uv_0.geometry} material={materials.material} position={[13.489, 29.447, -53.111]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder002_high_uv_0.geometry} material={materials.material} position={[13.551, 31.12, -75.801]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder003_high_uv_0.geometry} material={materials.material} position={[10.182, 27.233, -61.939]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cube010_high_uv_0.geometry} material={materials.material} position={[13.103, 7.05, 89.462]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder004_high_uv_0.geometry} material={materials.material} position={[5.255, 13.849, 96.743]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cube011_high_uv_0.geometry} material={materials.material} position={[13.432, -27.927, -24.417]} rotation={[-1.601, 0, -0.003]} scale={100} />
        <mesh geometry={nodes.Cylinder005_high_uv_0.geometry} material={materials.material} position={[13.424, -25.551, -21.854]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Circle_high_uv_0.geometry} material={materials.material} position={[10.176, -25.482, -22.09]} rotation={[-0.004, -0.003, 0]} scale={100} />
        <mesh geometry={nodes.Box_Piece_high_uv_0.geometry} material={materials.material} position={[12.803, 31.04, 218.522]} rotation={[-0.143, 1.568, 1.71]} scale={100} />
        <mesh geometry={nodes.Cylinder006_high_uv_0.geometry} material={materials.material} position={[12.804, 27.855, 218.535]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube012_high_uv_0.geometry} material={materials.material} position={[7.797, 10.882, 22.1]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube013_high_uv_0.geometry} material={materials.material} position={[3.462, 10.664, 43.196]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder007_high_uv_0.geometry} material={materials.material} position={[2.926, -5.443, 8.925]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder008_high_uv_0.geometry} material={materials.material} position={[0.918, -4.822, -22.51]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder009_high_uv_0.geometry} material={materials.material} position={[8.627, -21.265, -60.29]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder010_high_uv_0.geometry} material={materials.material} position={[24.927, -4.799, -94.554]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube015_high_uv_0.geometry} material={materials.material} position={[25.892, -4.687, -93.419]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube016_high_uv_0.geometry} material={materials.material} position={[25.891, -2.47, -93.428]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder012_high_uv_0.geometry} material={materials.material} position={[25.477, -3.335, -86.652]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder014_high_uv_0.geometry} material={materials.material} position={[26.758, 4.732, -88.524]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder015_high_uv_0.geometry} material={materials.material} position={[26.576, -3.556, -21.696]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder016_high_uv_0.geometry} material={materials.material} position={[26.468, -5.802, 17.695]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder017_high_uv_0.geometry} material={materials.material} position={[25.933, -9.207, -20.38]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder018_high_uv_0.geometry} material={materials.material} position={[25.953, -6.57, -28.277]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder019_high_uv_0.geometry} material={materials.material} position={[13.488, 28.896, -52.662]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cube019_high_uv_0.geometry} material={materials.material} position={[3.808, 27.21, 54.386]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder020_high_uv_0.geometry} material={materials.material} position={[5.51, 27.289, 54.433]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder021_high_uv_0.geometry} material={materials.material} position={[22.651, 11.867, -83.125]} rotation={[1.576, -1.289, 0.01]} scale={100} />
        <mesh geometry={nodes.Cube021_high_uv_0.geometry} material={materials.material} position={[13.095, 25.512, 89.867]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder022_high_uv_0.geometry} material={materials.material} position={[11.735, 30.867, -70.724]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder023_high_uv_0.geometry} material={materials.material} position={[2.224, 2.004, -44.966]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder024_high_uv_0.geometry} material={materials.material} position={[3.895, -2.593, 39.494]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Plane001_high_uv_0.geometry} material={materials.material} position={[12.553, -13.778, -24.551]} rotation={[-1.634, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder025_high_uv_0.geometry} material={materials.material} position={[5.128, -14.922, -21.062]} rotation={[-1.638, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder026_high_uv_0.geometry} material={materials.material} position={[25.939, 0.323, -58.451]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder027_high_uv_0.geometry} material={materials.material} position={[24.052, 3.968, 34.497]} rotation={[-0.143, 1.568, -1.432]} scale={100} />
        <mesh geometry={nodes.Cube022_high_uv_0.geometry} material={materials.material} position={[12.88, 16.786, 168.677]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cylinder029_high_uv_0.geometry} material={materials.material} position={[24.836, -3.878, 48.241]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cylinder030_high_uv_0.geometry} material={materials.material} position={[24.826, -0.875, 51.063]} rotation={[2.999, -1.568, 1.432]} scale={100} />
        <mesh geometry={nodes.Cube023_high_uv_0.geometry} material={materials.material} position={[13.197, 27.229, 52.79]} rotation={[-1.575, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube014_high_uv_0.geometry} material={materials.material} position={[13.484, -15.66, -44.949]} rotation={[-1.63, 0, 3.139]} scale={100} />
        <mesh geometry={nodes.Cube020_high_uv_0.geometry} material={materials.material} position={[13.313, -87.871, 27.269]} rotation={[-2.031, 0.001, 3.139]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/ak_12.glb')
