/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 1855_springfield_rifle_musket_-_game_asset.glb 
Author: Andy woodhead (https://sketchfab.com/Andywoodhead)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/1855-springfield-rifle-musket-game-asset-ac04cd41f99b48c2835206668635cf5e
Title: 1855 Springfield rifle musket - game asset
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function SpringfielMusketdModel(props) {
  const { nodes, materials } = useGLTF('/1855_springfield_rifle_musket_-_game_asset.glb')
  return (
    <group position={[-3,0,0]} scale={0.4} {...props} dispose={null}>
      <mesh geometry={nodes.Musket_10_Musket_10_0.geometry} material={materials.Musket_10} />
      <mesh geometry={nodes.Musket_07_Musket_07_0.geometry} material={materials.Musket_07} />
    </group>
  )
}

useGLTF.preload('/1855_springfield_rifle_musket_-_game_asset.glb')
