/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 g11.glb 
Author: GageCriscione (https://sketchfab.com/GageCriscione)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/g11-adcc143d66344019bf695d63299486b3
Title: G11
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function G11Model(props) {
  const { nodes, materials } = useGLTF('/g11.glb')
  return (
    <group scale={0.1} rotation={[0,1.65,0]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.G11_ModelMaterial__48} position={[-5.233, -50.16, -20.399]} />
      </group>
    </group>
  )
}

useGLTF.preload('/g11.glb')
