/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 low-poly_fn_f2000.glb 
Author: TastyTony (https://sketchfab.com/TastyTony)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-fn-f2000-6848de463d5444c0ba0022c1ca7cb85c
Title: Low-Poly FN F2000
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function FNF2000Model(props) {
  const { nodes, materials } = useGLTF('/low-poly_fn_f2000.glb')
  return (
    <group scale={0.01} {...props} dispose={null}>
      <group position={[159.676, 60.097, 0]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={112.508}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh geometry={nodes.Object_18.geometry} material={materials['Material.002']} skeleton={nodes.Object_18.skeleton} />
        <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Material} skeleton={nodes.Object_19.skeleton} />
        <skinnedMesh geometry={nodes.Object_20.geometry} material={materials['Material.004']} skeleton={nodes.Object_20.skeleton} />
        <skinnedMesh geometry={nodes.Object_21.geometry} material={materials['Material.006']} skeleton={nodes.Object_21.skeleton} />
        <skinnedMesh geometry={nodes.Object_22.geometry} material={materials['Material.003']} skeleton={nodes.Object_22.skeleton} />
        <skinnedMesh geometry={nodes.Object_23.geometry} material={materials['Material.001']} skeleton={nodes.Object_23.skeleton} />
        <skinnedMesh geometry={nodes.Object_24.geometry} material={materials['Material.005']} skeleton={nodes.Object_24.skeleton} />
        <skinnedMesh geometry={nodes.Object_25.geometry} material={materials['Material.010']} skeleton={nodes.Object_25.skeleton} />
        <skinnedMesh geometry={nodes.Object_26.geometry} material={materials['Material.009']} skeleton={nodes.Object_26.skeleton} />
        <skinnedMesh geometry={nodes.Object_27.geometry} material={materials['Material.008']} skeleton={nodes.Object_27.skeleton} />
        <skinnedMesh geometry={nodes.Object_28.geometry} material={materials['Material.007']} skeleton={nodes.Object_28.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('/low-poly_fn_f2000.glb')
