/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ar_rifle_10.glb 
Author: TORI106 (https://sketchfab.com/TORI106)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ar-rifle-10-75b2c308fb8a430fae06415a8fa680e4
Title: AR Rifle 10
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ar10Model(props) {
  const { nodes, materials } = useGLTF('/ar_rifle_10.glb')
  return (
    <group scale={0.02} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[91.955, 40.035, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material} />
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Material_001} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ar_rifle_10.glb')
