/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 m1_garand.glb 
Author: barracudazp (https://sketchfab.com/barracudazp)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m1-garand-b25045b6195948fe8c6837c9bd7c7cbc
Title: M1 Garand
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function M1GarandModel(props) {
  const { nodes, materials } = useGLTF('/m1_garand.glb')
  return (
    <group position={[0,1,0]} rotation={[0,1.5,0]} {...props} dispose={null}>
      <group scale={0.1}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Receiver_low_Garand_2_0.geometry} material={materials.Garand_2} />
          <mesh geometry={nodes.Receiver_low_Garand_1_0.geometry} material={materials.Garand_1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/m1_garand.glb')
