/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 adaptive_combat_rifle.glb 
Author: doomsentinel (https://sketchfab.com/doomsentinel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adaptive-combat-rifle-a18a8008a299430caa5f1fe05563c949
Title: Adaptive Combat Rifle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function ACRModel(props) {
  const { nodes, materials } = useGLTF('/adaptive_combat_rifle.glb')
  return (
    <group scale={0.025} rotation={[0,0,-0.25]} {...props} dispose={null}>
      <mesh geometry={nodes.Suppresor_Silencer_0.geometry} material={materials.Silencer} position={[142.138, 73.888, 0.211]} rotation={[-Math.PI / 2, -0.256, 0]} />
      <mesh geometry={nodes.Scope_Scope_0.geometry} material={materials.Scope} position={[-40.667, 50.157, 0.324]} rotation={[-Math.PI / 2, -0.256, 0]} />
      <mesh geometry={nodes.Foregrip_Foregrip_0.geometry} material={materials.Foregrip} position={[48.971, 26.637, -0.067]} rotation={[-Math.PI / 2, -0.256, 0]} />
      <mesh geometry={nodes.Pmag_Pmag_0.geometry} material={materials.Pmag} position={[-6.461, -10.603, -0.052]} rotation={[-Math.PI / 2, -0.256, 0]} />
      <mesh geometry={nodes.ACRRifle001_Rifle_0.geometry} material={materials.Rifle} position={[-35.21, -6.907, 0]} rotation={[-Math.PI / 2, -0.256, 0]} />
    </group>
  )
}

useGLTF.preload('/adaptive_combat_rifle.glb')
