/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 remington_model_95_double_derringer.glb 
Author: arekkusodesu (https://sketchfab.com/arekkusodesu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/remington-model-95-double-derringer-d5730f07610f4d6586999d7489370d6e
Title: Remington Model 95 Double Derringer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function RemingtonModel95Model(props) {
  const { nodes, materials } = useGLTF('/remington_model_95_double_derringer.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.08}>
        <mesh geometry={nodes.polySurface58_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface65_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface57_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface59_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface1_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCube6_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface64_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder59_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder60_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder66_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder65_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder41_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder40_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder39_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface53_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder28_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.qqqqwwww_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.pCylinder42_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface54_M_GUN1_0.geometry} material={materials.M_GUN1} scale={[1, 1, 1.033]} />
        <mesh geometry={nodes.pCube5_M_GUN1_0.geometry} material={materials.M_GUN1} />
        <mesh geometry={nodes.polySurface2_M_GUN1_0.geometry} material={materials.M_GUN1} scale={[1, 1, 1.033]} />
        <mesh geometry={nodes.polySurface62_M_GUN1_0.geometry} material={materials.M_GUN1} />
        <mesh geometry={nodes.polySurface67_M_GUN1_0.geometry} material={materials.M_GUN1} />
        <mesh geometry={nodes.polySurface68_M_GUN1_0.geometry} material={materials.M_GUN1} />
        <mesh geometry={nodes.polySurface69_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface70_M_GUN2_0.geometry} material={materials.M_GUN2} />
        <mesh geometry={nodes.polySurface71_M_GUN1_0.geometry} material={materials.M_GUN1} />
      </group>
    </group>
  )
}

useGLTF.preload('/remington_model_95_double_derringer.glb')
