/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 vepr_vpo_205-00.glb 
Author: yarogor (https://sketchfab.com/yarogor)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vepr-vpo-205-00-1c037285a1654db2b7686d57d79d7ce2
Title: VEPR VPO 205-00
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function VEPRModel(props) {
  const { nodes, materials } = useGLTF('/vepr_vpo_205-00.glb')
  return (
    <group scale={5} position={[0,1,0]} rotation={[0.1,1.6,0]} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Selector} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Bolt} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Button_upper} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Spring} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Protective_cup} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Bolt_ready} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Gas_tube_protector} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Stock} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Magazine} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Handguard} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Upper} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.Main_body} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.Spring_stopper} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.Handle_bottom} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.material} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.Trigger_guard} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.Spring2} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.Main_barrel} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.Trigger_goup} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.Piston} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.Handle} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.Flashhider} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.Backsight} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.Magwell} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/vepr_vpo_205-00.glb')
