/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 m1918a2_bar.glb 
Author: Shorty_Digitan (https://sketchfab.com/Shorty_Digitan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m1918a2-bar-f3eda10014fb44d4a6912ee9c742d67a
Title: M1918A2 BAR
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function M1918a2Model(props) {
  const { nodes, materials } = useGLTF('/m1918a2_bar.glb')
  return (
    <group scale={0.1} rotation={[0,1.6,0]} {...props} dispose={null}>
      <group position={[0, 2.391, 10.847]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes['body_body-metal_0'].geometry} material={materials['body-metal']} />
        <mesh geometry={nodes['body_body-metal-stock_0'].geometry} material={materials['body-metal-stock']} />
        <mesh geometry={nodes['body_body-wood_0'].geometry} material={materials['body-wood']} />
      </group>
      <group position={[0, 4.2, -6.272]} rotation={[-Math.PI / 2, 1.55, 0]} scale={100}>
        <mesh geometry={nodes['Grip_Grip-metal_0'].geometry} material={materials['Grip-metal']} />
        <mesh geometry={nodes['Grip_Grip-wood_0'].geometry} material={materials['Grip-wood']} />
      </group>
      <mesh geometry={nodes.magazine_Magazine_0.geometry} material={materials.Magazine} position={[0, -5.591, 12.069]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.sight_sight_0.geometry} material={materials.sight} position={[0, 7.242, 21.429]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.reciever_Reciever_0.geometry} material={materials.Reciever} position={[0.77, 5.351, 8.171]} rotation={[-Math.PI / 2, 0, 0]} scale={0.85} />
      <mesh geometry={nodes['bolt-handle_Material_0'].geometry} material={materials.Material} position={[-2.482, 2.512, 24.592]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
      <mesh geometry={nodes.trigger_Trigger_0.geometry} material={materials.Trigger} position={[0, -0.294, 23.51]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.296, 0.357, 0.357]} />
      <mesh geometry={nodes.Bipod_bipod_0.geometry} material={materials.bipod} position={[0.036, 4.485, -48.172]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/m1918a2_bar.glb')
