/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 low_poly_m4_carbine_lvoa-c.glb 
Author: Anysius (https://sketchfab.com/Anysius)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-m4-carbine-lvoa-c-ca2f2ab29c10454e92080f748436c1f8
Title: Low poly M4 Carbine Lvoa-C
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function LvoacModel(props) {
  const { nodes, materials } = useGLTF('/low_poly_m4_carbine_lvoa-c.glb')
  return (
    <group position={[-0.5,-2,0]} scale={0.0006} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001_1_117d9203-09e9-4f34-ba27-16fef371815d']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.014_77584dc4-3bb1-4b8a-a688-2ce1ba837fdb']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.015_bc719f23-e458-460b-b53e-d7516907adc2']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.016_8f2c7db7-0a43-47aa-b388-dcb6d1362d8c']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Material.017_5c3c8bfa-cde4-464d-9ca0-75beff87e482']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['Spanish_Style_cf8b2b08-88a7-4962-8829-ac44aa228fee']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['desert_tan_7c96658a-f088-459e-86f3-f33beae9e711']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['desert_tan_mag_9518e8ad-5068-4611-a33f-61b4e1f0ed2e']} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['metal_bright-ish_cb89522b-1c0b-4c36-97bf-7c7090c7c3ed']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['plastic_1_a66a8001-ec91-4d11-a023-5fc028b8f4ef']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001_8352b34e-a82a-4fa4-948b-8c6210b81879']} />
        <mesh geometry={nodes.Object_13.geometry} material={materials['Material.004_b0e1dc1d-378f-429c-bb31-757479ca1ceb']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.005_30a4b65f-20d7-46b2-9028-c7a7d4d50b7c']} />
        <mesh geometry={nodes.Object_15.geometry} material={materials['Material.006_47ae93b7-5658-4f88-a676-75a635bf3a0d']} />
        <mesh geometry={nodes.Object_16.geometry} material={materials['Material.007_50bd5bc6-c63a-4640-ad36-dabc697b3c6f']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.007_50bd5bc6-c63a-4640-ad36-dabc697b3c6f']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['Material_5ae405a9-6178-428d-b10c-6b1e28e06a48']} />
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_m4_carbine_lvoa-c.glb')
