/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ak-47_kalashnikov.glb 
Author: Jeyhun1985 (https://sketchfab.com/Jeyhun1985)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ak-47-kalashnikov-5d08c2e227d04a0f87cd5a005e6b56d1
Title: AK-47 Kalashnikov
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function AK47Model(props) {
  const { nodes, materials } = useGLTF('/ak-47_kalashnikov.glb')
  return (
    <group position={[0,0,1]} {...props} dispose={null}>
      <group rotation={[0,1.5,0]} position={[-0.006, 0.109, -0.514]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/ak-47_kalashnikov.glb')
