/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 bren_mk_2.glb 
Author: Shorty_Digitan (https://sketchfab.com/Shorty_Digitan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bren-mk-2-49cdc2f6f7054083a448fe54b9c07123
Title: Bren Mk 2
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function BrenMk2Model(props) {
  const { nodes, materials } = useGLTF('/bren_mk_2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.2,0,1]} rotation={[0,-1.7,0]} scale={0.06}>
        <group position={[0, 3.397, -30.997]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Bren_Bren_Main_0.geometry} material={materials.Bren_Main} />
          <mesh geometry={nodes.Bren_Bren_wood_0.geometry} material={materials.Bren_wood} />
        </group>
        <group position={[0, 9.616, 10.445]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Grip_2_Bren_Main_0.geometry} material={materials.Bren_Main} />
          <mesh geometry={nodes.Grip_2_Bren_wood_0.geometry} material={materials.Bren_wood} />
        </group>
        <mesh geometry={nodes.Magazine_Bren_Magazine_0.geometry} material={materials.Bren_Magazine} position={[0, 18.588, -4.192]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Grip_1_Bren_Main_0.geometry} material={materials.Bren_Main} position={[0, 4.751, 12.592]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Bipod_R_Bren_Main_0.geometry} material={materials.Bren_Main} position={[0, -4.432, 27.998]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Bipod_1_Bren_Main_0.geometry} material={materials.Bren_Main} position={[0, 1.769, 27.998]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Bipod_Spring_Bren_Main_0.geometry} material={materials.Bren_Main} position={[0, -6.637, 27.995]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Bipod_2_Bren_Main_0.geometry} material={materials.Bren_Main} position={[0, -2.51, 27.998]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Trigger_Bren_Main_0.geometry} material={materials.Bren_Main} position={[0, -1.279, -19.938]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Fire_selector_Bren_Main_0.geometry} material={materials.Bren_Main} position={[1.853, -0.015, -22.095]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Rear_sight_Bren_rear_sight_0.geometry} material={materials.Bren_rear_sight} position={[0, 7.52, -28.729]} rotation={[-Math.PI, 0, 0]} scale={100} />
        <mesh geometry={nodes.Rear_sight_circle_Bren_rear_sight_0.geometry} material={materials.Bren_rear_sight} position={[0, 10.283, -28.849]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Magazine_release_Bren_Main_0.geometry} material={materials.Bren_Main} position={[0, 9.365, -18.359]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Cocking_handle_Bren_Main_0.geometry} material={materials.Bren_Main} position={[-2.41, 1.786, -16.126]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Bipod_L_Bren_Main_0.geometry} material={materials.Bren_Main} position={[0, -4.432, 27.998]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('/bren_mk_2.glb')
